### ISSUE TITLE
Подготовить к работе RPi

### ISSUE THREAD

**Issue by ikherty** [ikherty/ValiNIR#1]
Скачать образ, настроить ssh, сделать клон образа

**Comment by ikherty** [comment]
1) Скачать raspbian-stretch-lite образ с сайта https://www.raspberrypistarterkits.com/downloads/raspbian/
2) Прошить образ на флешку RPi Zero W через RPi Imager или dd
3) Поменять конфиг на флешке для подключения RPi к роутеру: в файле /etc/wpa_supplicant/wpa_supplicant.conf
следующее содержимое:
```
 ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
 update_config=1
 country=GB
 network={
 ssid=<<ИМЯ_ТОЧКИ_ДОСТУПА>>
 psk=passwd
 }
```
4) вернуть флешку в RPi, подать питание, дождаться загрузки системы и с наземной станции найти IP адрес RPi командой

> nmap -sn 192.168.1.0/24

5) (для удобства) поменять хостнейм и пароль для упрощенного подключения по ssh:

> sudo nano /etc/hosts
> sudo passwd pi

**Comment by ikherty** [comment]
@mituritsyn надо будет сделать клон образа

**Comment by mituritsyn** [comment]
@ikherty завел таску, можешь сделать)
