### ISSUE TITLE
Пробросить видеопоток на виртуальную камеру

### ISSUE THREAD

**Issue by dimazollo** [ikherty/ValiNIR#15]
https://askubuntu.com/questions/881305/is-there-any-way-ffmpeg-send-video-to-dev-video0-on-ubuntu

**Comment by dimazollo** [comment]
https://github.com/umlaeute/v4l2loopback

```
sudo apt install v4l2loopback-dkms
sudo modprobe v4l2loopback
```

> You can check which loopback devices are created by listing contents of /sys/devices/virtual/video4linux directory. E.g. if there are two v4l2loopback devices /dev/video0 and /dev/video3 you would get:
> ```
> $ ls -1 /sys/devices/virtual/video4linux
> video0
> video3
> ```

**Comment by dimazollo** [comment]
@mituritsyn please take a look. Let's try that approach in VM with configured clover environment.

**Comment by ikherty** [comment]
udp поток с rpi через ffmpeg в /dev/video0 виртуалки

**Comment by mituritsyn** [comment]
самый рабочий на данный момент вариант:
запустить на малине:

gst-launch-1.0 rpicamsrc bitrate=1000000 ! 'video/x-h264,width=640,height=480' ! h264parse ! queue ! rtph264pay config-interval=1 pt=96 ! gdppay ! udpsink host=192.168.101.[ip наземки] port=5000

на наземке:
sudo apt install v4l2loopback-dkms
sudo modprobe v4l2loopback

gst-launch-1.0 udpsrc port=5000 ! gdpdepay ! rtph264depay ! avdec_h264 ! videoconvert ! v4l2sink device=/dev/video0

**Comment by mituritsyn** [comment]
rpi:
libcamera-vid -t 0 -n --inline -o - | gst-launch-1.0 fdsrc fd=0 ! udpsink host=192.168.101.7 port=5000 sync=false
gs:
gst-launch-1.0 udpsrc port=5000 ! decodebin ! videoconvert !  v4l2sink device=/dev/video0
