### ISSUE TITLE
Скачать образы clover

### ISSUE THREAD

**Issue by ikherty** [ikherty/ValiNIR#2]
Настроить окружение. 
VMWARE ( нет варианта для макОс): https://customerconnect.vmware.com/en/downloads/details?downloadGroup=WKST-PLAYER-1700&productId=1377&rPId=97014
Clover_vm: https://github.com/CopterExpress/clover_vm/releases/tag/v1.3

**Comment by ikherty** [comment]
ready

**Comment by mituritsyn** [comment]
done

**Comment by dimazollo** [comment]
Tried vbox v6 and v7 for mac and windows, vmware fusion for mac, vmware workstation for windows - and I have had troubles with all of them. VM hypervisors s*cks
